"use client";

import { ArrowLeft, BrainCircuit, CalendarClock, Check, Pencil, Plus, X } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ApiError, api } from "@/lib/api";

type Card = { id: string; sourceType: "INTERVIEW" | "KNOWLEDGE" | "AGENT" | "WEB"; sourceLabel: string | null; sourceUrl: string | null; front: string; back: string; tags: string[]; status: "NEW" | "LEARNING" | "REVIEW" | "SUSPENDED"; nextReviewAt: string; intervalDays: number; repetitions: number; lapses: number };
const sourceLabel: Record<Card["sourceType"], string> = { INTERVIEW: "面试原题", KNOWLEDGE: "我的题库", AGENT: "Ardor 训练题", WEB: "网络题" };

export default function CardsPage() {
  const router = useRouter();
  const [cards, setCards] = useState<Card[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [editing, setEditing] = useState<Card | null>(null);
  const [revealed, setRevealed] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async () => { try { setCards(await api<Card[]>("/api/memory-cards")); } catch (reason) { if (reason instanceof ApiError && reason.status === 401) router.replace("/login"); else setError(reason instanceof Error ? reason.message : "无法加载记忆卡"); } }, [router]);
  useEffect(() => { let active = true; api<Card[]>("/api/memory-cards").then((items) => { if (active) setCards(items); }).catch((reason) => { if (!active) return; if (reason instanceof ApiError && reason.status === 401) router.replace("/login"); else setError(reason instanceof Error ? reason.message : "无法加载记忆卡"); }); return () => { active = false; }; }, [router]);
  const dueCards = useMemo(() => cards.filter((card) => card.status !== "SUSPENDED" && new Date(card.nextReviewAt) <= new Date()), [cards]);
  const card = dueCards[0] ?? null;

  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(""); try { const content = { front: data.get("front"), back: data.get("back"), tags: String(data.get("tags") ?? "").split(/[，,]/).map((x) => x.trim()).filter(Boolean) }; await api<Card>(editing ? `/api/memory-cards/${editing.id}` : "/api/memory-cards", { method: editing ? "PUT" : "POST", body: JSON.stringify(editing ? content : { ...content, sourceType: data.get("sourceType"), sourceLabel: data.get("sourceLabel"), sourceUrl: data.get("sourceUrl") }) }); setShowForm(false); setEditing(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : editing ? "保存修改失败" : "建卡失败"); } finally { setBusy(false); } }
  async function review(rating: "AGAIN" | "HARD" | "GOOD" | "EASY") { if (!card) return; setBusy(true); setError(""); try { await api<Card>(`/api/memory-cards/${card.id}/reviews`, { method: "POST", body: JSON.stringify({ rating }) }); setRevealed(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存复习结果失败"); } finally { setBusy(false); } }

  return <main className="ardor-workbench min-h-screen px-5 pb-16 pt-6 text-[#1d1d1f] md:px-10"><div className="mx-auto max-w-7xl">
    <div className="flex items-center justify-between"><Link href="/app" className="inline-flex items-center gap-2 rounded-full px-3 py-2 text-sm text-stone-500 hover:bg-white/70 hover:text-stone-900"><ArrowLeft className="size-4" />返回 Ardor</Link><button onClick={() => { setEditing(null); setShowForm(true); }} className="inline-flex items-center gap-2 rounded-full bg-stone-950 px-5 py-2.5 text-sm font-medium text-white"><Plus className="size-4" />新建卡片</button></div>
    <header className="pb-10 pt-12 md:pt-16"><p className="text-sm font-medium text-violet-600">MEMORY CARDS</p><h1 className="mt-3 text-5xl font-semibold tracking-[-0.055em] md:text-7xl">把薄弱点，练成长期记忆。</h1></header>
    {error && <div className="mb-5 rounded-2xl bg-red-50/90 px-5 py-4 text-sm text-red-700">{error}</div>}
    <div className="grid gap-6 lg:grid-cols-[1.15fr_0.85fr]"><section className="ardor-panel rounded-[2.25rem] p-6 md:p-9"><div className="flex items-center justify-between"><div><p className="text-sm text-violet-600">TODAY</p><h2 className="mt-2 text-3xl font-semibold">{dueCards.length ? `${dueCards.length} 张待复习` : "今天已完成"}</h2></div><BrainCircuit className="size-7 text-violet-500" /></div>{card ? <div className="mt-8"><button onClick={() => setRevealed(true)} className="min-h-72 w-full rounded-[2rem] bg-white/75 p-8 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-violet-100 px-3 py-1 text-xs text-violet-700">{sourceLabel[card.sourceType]}</span>{card.tags.map((tag) => <span key={tag} className="rounded-full bg-stone-100 px-3 py-1 text-xs text-stone-500">{tag}</span>)}</div><h3 className="mt-8 text-2xl font-semibold leading-relaxed">{card.front}</h3>{revealed ? <div className="mt-7 whitespace-pre-wrap border-t border-stone-200 pt-6 text-sm leading-7 text-stone-600">{card.back}</div> : <p className="mt-12 text-sm text-stone-400">点击查看答案</p>}</button>{revealed && <div className="mt-5 grid grid-cols-4 gap-2">{([['AGAIN','忘记'],['HARD','困难'],['GOOD','掌握'],['EASY','轻松']] as const).map(([value,label]) => <button disabled={busy} key={value} onClick={() => review(value)} className="rounded-2xl bg-white/75 px-2 py-3 text-sm font-medium shadow-sm hover:bg-white disabled:opacity-40">{label}</button>)}</div>}</div> : <div className="mt-10 grid min-h-72 place-items-center rounded-[2rem] bg-white/45 text-center"><div><Check className="mx-auto size-8 text-emerald-500" /><p className="mt-4 text-sm text-stone-500">下一张卡片会按计划出现</p></div></div>}</section>
      <aside className="ardor-soft-panel rounded-[2rem] p-5 md:p-6"><div className="flex items-center justify-between"><h2 className="font-semibold">全部卡片</h2><span className="text-xs text-stone-400">{cards.length}</span></div><div className="mt-5 max-h-[36rem] space-y-2 overflow-y-auto">{cards.map((item) => <div key={item.id} className="group rounded-2xl bg-white/70 p-4"><div className="flex items-start gap-3"><CalendarClock className="mt-0.5 size-4 shrink-0 text-violet-500" /><div className="min-w-0 flex-1"><p className="line-clamp-2 text-sm font-medium leading-5">{item.front}</p><p className="mt-2 text-xs text-stone-400">{sourceLabel[item.sourceType]} · {new Date(item.nextReviewAt).toLocaleDateString("zh-CN", { month: "short", day: "numeric" })}</p></div><button aria-label="编辑记忆卡" onClick={() => { setEditing(item); setShowForm(true); }} className="rounded-lg p-2 text-stone-400 opacity-60 hover:bg-white hover:text-stone-800 group-hover:opacity-100"><Pencil className="size-3.5" /></button></div></div>)}</div></aside></div>
  </div>{showForm && <div className="fixed inset-0 z-50 grid place-items-center bg-black/20 p-4 backdrop-blur-sm"><section className="ardor-panel max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[2rem] p-6 md:p-8"><div className="mb-6 flex items-center justify-between"><h2 className="text-2xl font-semibold">{editing ? "编辑记忆卡" : "新建记忆卡"}</h2><button aria-label="关闭" onClick={() => { setShowForm(false); setEditing(null); }} className="rounded-full p-2 text-stone-400 hover:bg-white"><X className="size-5" /></button></div><form key={editing?.id ?? "new"} onSubmit={save} className="space-y-4">{!editing && <><select name="sourceType" className="field"><option value="KNOWLEDGE">我的题库</option><option value="AGENT">训练题</option><option value="WEB">网络题</option></select><input name="sourceLabel" maxLength={240} className="field" placeholder="来源名称（可选）" /><input name="sourceUrl" maxLength={1000} className="field" placeholder="网络来源链接（网络题必填）" /></>}<textarea name="front" required rows={3} defaultValue={editing?.front ?? ""} className="field resize-y" placeholder="问题" /><textarea name="back" required rows={6} defaultValue={editing?.back ?? ""} className="field resize-y" placeholder="参考答案或回答框架" /><input name="tags" defaultValue={editing?.tags.join(", ") ?? ""} className="field" placeholder="标签，用逗号分隔" /><button disabled={busy} className="w-full rounded-full bg-stone-950 px-5 py-3 text-sm font-medium text-white disabled:opacity-50">{busy ? "保存中…" : editing ? "保存修改" : "保存并安排复习"}</button></form></section></div>}</main>;
}
