package com.projectardor.usage;

public enum UsageFeature {
    AGENT_CHAT,
    RESUME_ANALYSIS,
    INTERVIEW_CREATE,
    INTERVIEW_EVALUATION,
    INTERVIEW_RECAP,
    INTERVIEW_REPLAY,
    LEARNING_PLAN,
    LEARNING_ATTEMPT,
    KNOWLEDGE_UPLOAD,
    KNOWLEDGE_SEARCH,
    KNOWLEDGE_RESEARCH,
    CONNECTION_TEST,
    VOICE_ASR,
    VOICE_TTS
}
