"use client";

import { ArrowLeft, ArrowRight, ChevronRight, FileText, Plus, Sparkles, Trash2, X } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ApiError, api } from "@/lib/api";

type Performance = "STRONG" | "MIXED" | "WEAK" | "UNKNOWN";
type Question = { id: string; sequenceNumber: number; questionText: string; candidateAnswer: string | null; followUps: string[]; assessment: string; performance: Performance; weaknessReason: string | null; betterAnswer: string | null; tags: string[] };
type Recap = { id: string; title: string; company: string | null; targetRole: string | null; occurredAt: string | null; overview: string; strengths: string[]; weaknesses: string[]; createdAt: string; questions: Question[] };
type RecapTask = { jobId: string | null; recapId: string | null; status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED"; errorMessage?: string | null };
const performanceLabel: Record<Performance, string> = { STRONG: "稳", MIXED: "需巩固", WEAK: "薄弱", UNKNOWN: "待确认" };
const performanceStyle: Record<Performance, string> = { STRONG: "bg-emerald-100 text-emerald-700", MIXED: "bg-amber-100 text-amber-700", WEAK: "bg-rose-100 text-rose-700", UNKNOWN: "bg-stone-100 text-stone-500" };

export default function RecapsPage() {
  const router = useRouter();
  const [recaps, setRecaps] = useState<Recap[]>([]);
  const [jobs, setJobs] = useState<RecapTask[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async () => { try { const [items, tasks] = await Promise.all([api<Recap[]>("/api/interview-recaps"), api<RecapTask[]>("/api/interview-recaps/jobs")]); setRecaps(items); setJobs(tasks); const requested = new URLSearchParams(window.location.search).get("selected"); setSelectedId((id) => requested && items.some((x) => x.id === requested) ? requested : id && items.some((x) => x.id === id) ? id : items[0]?.id ?? null); } catch (reason) { if (reason instanceof ApiError && reason.status === 401) router.replace("/login"); else setError(reason instanceof Error ? reason.message : "无法加载面经"); } }, [router]);
  useEffect(() => { const first = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(first); }, [load]);
  const selected = recaps.find((item) => item.id === selectedId) ?? null;
  const activeJobs = jobs.filter((job) => job.status === "QUEUED" || job.status === "RUNNING");
  const failedJobs = jobs.filter((job) => job.status === "FAILED");
  useEffect(() => {
    if (activeJobs.length === 0) return;
    const timer = window.setTimeout(() => void load(), 4000);
    return () => window.clearTimeout(timer);
  }, [activeJobs.length, load]);
  async function organize(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(""); try { const task = await api<RecapTask>("/api/interview-recaps", { method: "POST", body: JSON.stringify({ content: data.get("content") }) }); setShowForm(false); if (task.status === "COMPLETED" && task.recapId) router.push(`/app/recaps?selected=${task.recapId}`); else router.push("/app?notice=recap-queued"); } catch (reason) { setError(reason instanceof Error ? reason.message : "提交失败"); } finally { setBusy(false); } }
  async function remove(recap: Recap) { if (!window.confirm(`删除“${recap.title}”？`)) return; try { await api<void>(`/api/interview-recaps/${recap.id}`, { method: "DELETE" }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "删除失败"); } }

  return <main className="ardor-workbench min-h-screen px-5 pb-16 pt-6 text-[#1d1d1f] md:px-10"><div className="mx-auto max-w-7xl">
    <div className="flex items-center justify-between"><Link href="/app" className="inline-flex items-center gap-2 rounded-full px-3 py-2 text-sm text-stone-500 hover:bg-white/70 hover:text-stone-900"><ArrowLeft className="size-4" />返回 Ardor</Link><button onClick={() => setShowForm(true)} className="inline-flex items-center gap-2 rounded-full bg-stone-950 px-5 py-2.5 text-sm font-medium text-white"><Plus className="size-4" />整理面经</button></div>
    <header className="pb-10 pt-12 md:pt-16"><p className="text-sm font-medium text-violet-600">INTERVIEW RECAP</p><h1 className="mt-3 text-5xl font-semibold tracking-[-0.055em] md:text-7xl">看清每一次进步。</h1></header>
    {error && <div className="mb-5 rounded-2xl bg-red-50/90 px-5 py-4 text-sm text-red-700">{error}</div>}
    <div className="grid gap-6 lg:grid-cols-[0.7fr_1.3fr]"><section className="ardor-soft-panel h-fit rounded-[2rem] p-4"><div className="space-y-2">{activeJobs.map((job) => <div key={job.jobId} className="flex items-center gap-3 rounded-2xl bg-white/60 p-4"><span className="size-2 animate-pulse rounded-full bg-violet-500" /><span className="text-sm text-stone-500">正在后台整理…</span></div>)}{failedJobs.slice(0, 2).map((job) => <div key={job.jobId} className="rounded-2xl bg-rose-50/70 p-4 text-sm text-rose-700">整理失败：{job.errorMessage ?? "请重新提交"}</div>)}{recaps.map((recap) => { const weak = recap.questions.filter((q) => q.performance === "WEAK" || q.performance === "MIXED").length; return <button key={recap.id} onClick={() => setSelectedId(recap.id)} className={`flex w-full items-center gap-3 rounded-2xl p-4 text-left transition ${selectedId === recap.id ? "bg-white shadow-sm" : "hover:bg-white/70"}`}><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-violet-100 text-violet-600"><FileText className="size-4" /></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{recap.title}</strong><small className="mt-1 block text-stone-400">{recap.questions.length} 题 · {weak} 项需巩固</small></span><ChevronRight className="size-4 text-stone-300" /></button>; })}{recaps.length === 0 && activeJobs.length === 0 && <button onClick={() => setShowForm(true)} className="w-full rounded-2xl border border-dashed border-stone-300 px-5 py-12 text-sm text-stone-400 hover:bg-white/50">粘贴第一次面试内容</button>}</div></section><section className="ardor-panel min-h-[34rem] rounded-[2.25rem] p-6 md:p-9">{selected ? <Report recap={selected} onDelete={() => remove(selected)} /> : <div className="grid h-96 place-items-center text-sm text-stone-400">{activeJobs.length ? "报告完成后会出现在这里" : "选择一份面经"}</div>}</section></div>
  </div>{showForm && <div className="fixed inset-0 z-50 grid place-items-center bg-black/20 p-4 backdrop-blur-sm"><section className="ardor-panel max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[2rem] p-6 md:p-8"><div className="mb-6 flex items-center justify-between"><h2 className="text-2xl font-semibold">整理一场面试</h2><button aria-label="关闭" onClick={() => setShowForm(false)} className="rounded-full p-2 text-stone-400 hover:bg-white"><X className="size-5" /></button></div><form onSubmit={organize} className="space-y-4"><textarea name="content" required minLength={30} maxLength={50000} rows={16} className="field resize-y" placeholder="粘贴转录、回忆或整理过的内容…" /><button disabled={busy} className="w-full rounded-full bg-stone-950 px-5 py-3 text-sm font-medium text-white disabled:opacity-50">{busy ? "正在逐题整理…" : "生成面经"}</button></form></section></div>}</main>;
}

function Report({ recap, onDelete }: { recap: Recap; onDelete: () => void }) {
  const optimizeHref = `/app?new=1&prefill=${encodeURIComponent("根据我这次面试情况帮我生成记忆卡")}&contextType=RECAP&contextId=${recap.id}&contextLabel=${encodeURIComponent(recap.title)}`;
  return <div><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2">{recap.company && <span className="rounded-full bg-violet-100 px-3 py-1 text-xs text-violet-700">{recap.company}</span>}{recap.targetRole && <span className="rounded-full bg-stone-100 px-3 py-1 text-xs text-stone-600">{recap.targetRole}</span>}</div><h2 className="mt-4 text-3xl font-semibold tracking-tight">{recap.title}</h2><p className="mt-4 text-sm leading-7 text-stone-600">{recap.overview}</p><Link href={optimizeHref} className="mt-5 inline-flex items-center gap-2 rounded-full bg-stone-950 px-5 py-2.5 text-sm font-medium text-white hover:bg-black">优化计划<ArrowRight className="size-4" /></Link></div><button aria-label="删除面经" onClick={onDelete} className="rounded-full p-2 text-stone-300 hover:bg-rose-50 hover:text-rose-500"><Trash2 className="size-4" /></button></div>{(recap.strengths.length > 0 || recap.weaknesses.length > 0) && <div className="mt-8 grid gap-3 md:grid-cols-2">{recap.strengths.length > 0 && <Summary title="做得不错" items={recap.strengths} tone="emerald" />}{recap.weaknesses.length > 0 && <Summary title="优先补强" items={recap.weaknesses} tone="rose" />}</div>}<div className="mt-10 space-y-5">{recap.questions.map((q) => <article key={q.id} className="rounded-[1.75rem] bg-white/65 p-5 md:p-7"><div className="flex items-start gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-stone-950 text-xs text-white">{q.sequenceNumber}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-semibold leading-7">{q.questionText}</h3><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs ${performanceStyle[q.performance]}`}>{performanceLabel[q.performance]}</span></div>{q.tags.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{q.tags.map((tag) => <span key={tag} className="rounded-full bg-stone-100 px-2.5 py-1 text-[11px] text-stone-500">{tag}</span>)}</div>}</div></div><div className="mt-5 space-y-5 text-sm leading-7 md:pl-11">{q.candidateAnswer && <Section title="当时回答" text={q.candidateAnswer} />}{q.followUps.length > 0 && <section><h4 className="text-xs font-semibold uppercase tracking-wider text-stone-400">追问</h4><ul className="mt-1 space-y-1 text-stone-600">{q.followUps.map((x) => <li key={x}>· {x}</li>)}</ul></section>}<Section title="复盘" text={q.assessment} />{q.weaknessReason && <Section title="薄弱点" text={q.weaknessReason} danger />}{q.betterAnswer && <section className="rounded-2xl bg-violet-50/80 p-4"><h4 className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-violet-500"><Sparkles className="size-3.5" />更好的回答思路</h4><p className="mt-2 whitespace-pre-wrap text-violet-950/75">{q.betterAnswer}</p></section>}</div></article>)}</div></div>;
}
function Summary({ title, items, tone }: { title: string; items: string[]; tone: "emerald" | "rose" }) { return <div className={`rounded-2xl p-5 ${tone === "emerald" ? "bg-emerald-50/70" : "bg-rose-50/70"}`}><h3 className="text-sm font-semibold">{title}</h3><ul className="mt-3 space-y-2 text-sm leading-6 opacity-75">{items.map((x) => <li key={x}>· {x}</li>)}</ul></div>; }
function Section({ title, text, danger = false }: { title: string; text: string; danger?: boolean }) { return <section><h4 className={`text-xs font-semibold uppercase tracking-wider ${danger ? "text-rose-400" : "text-stone-400"}`}>{title}</h4><p className={`mt-1 whitespace-pre-wrap ${danger ? "text-rose-700/80" : "text-stone-600"}`}>{text}</p></section>; }
